- name: Create Config file
  ansible.builtin.template:
    src: job.xml
    dest: /tmp/job.xml

- name: Create
  community.general.jenkins_job:
    config: "{{ lookup('file', '/tmp/job.xml') }}"
    name: "{{item}}"
    url: http://172.31.8.255:8080
    user: admin
    password: "{{jenkins_password}}"
